### PR TITLE
implement updateTree & getTreesByVisibilityStatus

### PR DESCRIPTION
**Pull request by raustin9**
updateTree:
- looks for tree in database and updates it with new information given

getTreesByVisibilityStatus:
- returns trees from database based on whether or not they are published or unpublished

### CODE REVIEW

**Review by tbatk — APPROVED** [review]

**Review by andlrutt — APPROVED** [review]
Looks good! Thanks for adding the 'published' attribute to the type and schema. The only thing I am concerned about here is if a tree is not able to be found in the DB, it might be a good idea to check the return value of `updateTree()` and throw an error, in case someone deletes just before someone updates it. @trevormangrum tell me what you think, but searching by ID might also be a good idea, just a tiny bit faster, since each will have a unique id regardless, and mongo will only have to match that one field

**Comment by tbatk** [comment]
> Looks good! Thanks for adding the 'published' attribute to the type and schema. The only thing I am concerned about here is if a tree is not able to be found in the DB, it might be a good idea to check the return value of `updateTree()` and throw an error, in case someone deletes just before someone updates it. @trevormangrum tell me what you think, but searching by ID might also be a good idea, just a tiny bit faster, since each will have a unique id regardless, and mongo 
will only have to match that one field

I think you're right, we may want to consider implementing some sort of error handling for the case you mentioned. I didn't consider that initially, but I think it's best to have just in case. We modeled `updateTree` after Kemal's `updateChapter` from the MindVersity project. In `updateChapter`, Kemal uses a `queryChapter` object, which only contains the _id for the chapter to look for. We use a `queryTree` with the same premise here. I'm not exactly sure why Kemal implemented it this way, but it works well. We can change if it you like, but I think it should be fine.

**Comment by andlrutt** [comment]
> > Looks good! Thanks for adding the 'published' attribute to the type and schema. The only thing I am concerned about here is if a tree is not able to be found in the DB, it might be a good idea to check the return value of `updateTree()` and throw an error, in case someone deletes just before someone updates it. @trevormangrum tell me what you think, but searching by ID might also be a good idea, just a tiny bit faster, since each will have a unique id regardless, and mongo
> > will only have to match that one field
> 
> I think you're right, we may want to consider implementing some sort of error handling for the case you mentioned. I didn't consider that initially, but I think it's best to have just in case. We modeled `updateTree` after Kemal's `updateChapter` from the MindVersity project. In `updateChapter`, Kemal uses a `queryChapter` object, which only contains the _id for the chapter to look for. We use a `queryTree` with the same premise here. I'm not exactly sure why Kemal implemented it this way, but it works well. We can change if it you like, but I think it should be fine.

Ah, that makes sense. So whenever we call it, we will have to make a new tree?

**Comment by tbatk** [comment]
> > > Looks good! Thanks for adding the 'published' attribute to the type and schema. The only thing I am concerned about here is if a tree is not able to be found in the DB, it might be a good idea to check the return value of `updateTree()` and throw an error, in case someone deletes just before someone updates it. @trevormangrum tell me what you think, but searching by ID might also be a good idea, just a tiny bit faster, since each will have a unique id regardless, and mongo
> > > will only have to match that one field
> > 
> > 
> > I think you're right, we may want to consider implementing some sort of error handling for the case you mentioned. I didn't consider that initially, but I think it's best to have just in case. We modeled `updateTree` after Kemal's `updateChapter` from the MindVersity project. In `updateChapter`, Kemal uses a `queryChapter` object, which only contains the _id for the chapter to look for. We use a `queryTree` with the same premise here. I'm not exactly sure why Kemal implemented it this way, but it works well. We can change if it you like, but I think it should be fine.
> 
> Ah, that makes sense. So whenever we call it, we will have to make a new tree?

I think we would just create a new object with the Tree type, then set that tree's `_id` to the id of the tree we're looking to edit

**Pull request merged**
