### PR TITLE
Tlovett2/tkw 28 auth0

### PR DESCRIPTION
**Pull request by tlovett2**
I added an auth0 login and logout button on the home page. The login button, on successful login, will redirect to the admin page. Added a logout button and a welcome message to the admin page.

### CODE REVIEW

**Review by rluberto — APPROVED** [review]
Everything looks good. Thank you for getting this done.

**Review by tbatk — CHANGES_REQUESTED** [review]
I think auth0 has a package specifically for Next.js that has an easier implementation and should work better for our project. I think it all requires you to do is set up an API route. Try using that approach instead.

**Review by andlrutt — COMMENTED** [review]
I pulled the branch and tried running it, but ran into an error, shown below

image

Any idea what's going on with this? I made sure to run `yarn`

**Comment by tlovett2** [comment]
Thanks for the feedback! Trevor, I did not know that was a thing, but I just updated it to use the '@auth0/nextjs-auth0' package instead of the react package and you were right, much less headache was involved. Andrew, I am not entirely sure, I may have not added it as a dependency, which should also be fixed now. Please let me know if there's anything else I can fix.

**Review by tbatk — CHANGES_REQUESTED** [review]
Everything looks good! I think there's just a few small changes left that need to be made. The `<UserProvider>` component from auth0 should be the wrapper in `src/pages/_app.tsx`. You'll have to create that file. Next.js has a guide for how to make it [here](https://nextjs.org/docs/basic-features/typescript#custom-app). The files changed in GitHub also says that the admin pages were deleted entirely. Please restore them if you can.

**Comment by andlrutt** [comment]
> Thanks for the feedback! Trevor, I did not know that was a thing, but I just updated it to use the '@auth0/nextjs-auth0' package instead of the react package and you were right, much less headache was involved. Andrew, I am not entirely sure, I may have not added it as a dependency, which should also be fixed now. Please let me know if there's anything else I can fix.

Works now! Thanks. Pending Trevor's changes, looks good!

**Review by tbatk — APPROVED** [review]

**Pull request merged**
